[package]
name = "node_editor"
version = "0.0.1"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Node editor UI using imgui-rs as backend, made for aflak project"
license = "GPL-3.0-only"

[dependencies]
aflak_imgui = { path = "../../imgui-rs", version = "0.20.1" }
aflak_cake = { path = "../aflak_cake", version = "0.0.1" }
rayon = "1.0"
ron = "0.2"
serde = "1.0"
serde_derive = "1.0"
