[package]
name = "node_editor"
version = "0.1.0"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]

[dependencies]
imgui = { path = "../../imgui-rs" }
aflak_cake = { path = "../aflak_cake" }
rayon = "1.0"
ron = "0.2"
serde = "1.0"
serde_derive = "1.0"
