[package]
name = "aflak_imgui_glium_support"
version = "0.0.3"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Support crate for using glium with imgui, made for aflak project"
license = "GPL-3.0-only"

[dependencies]
glium = { git = "https://github.com/malikolivier/glium", rev = "d6ac886143198014c6dd254bcfb23422a0df6307" }
imgui = { path = "../../imgui-rs", version = "0.0.22-pre" }
imgui-glium-renderer = { path = "../../imgui-rs/imgui-glium-renderer", version = "0.0.22-pre" }
