[package]
name = "aflak_plot"
version = "0.0.1"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Plotting library using imgui made for aflak"
license = "GPL-3.0-only"

[dependencies]
glium = "0.22"
imgui = { path = "../../imgui-rs", version = "0.0.21-pre" }
imgui-glium-renderer = { path = "../../imgui-rs/imgui-glium-renderer", version = "0.0.21-pre" }
ndarray = "0.11"

[dev-dependencies]
imgui_glium_support = { path = "../imgui_glium_support" }
