[package]
name = "aflak_plot"
version = "0.0.1"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Plotting library using imgui made for aflak"
license = "GPL-3.0-only"

[dependencies]
glium = "0.22"
aflak_imgui = { path = "../../imgui-rs", version = "0.18.1" }
aflak_imgui-glium-renderer = { path = "../../imgui-rs/imgui-glium-renderer", version = "0.18.1" }
ndarray = "0.11"

[dev-dependencies]
ui_image2d = { path = "../ui_image2d" }
imgui_glium_support = { path = "../imgui_glium_support" }
