before_script:
  - rustc --version
  - git submodule update --init --recursive
  - cd src

nightly:
  image: rustdocker/rust:nightly
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose

fmt:
  image: rustdocker/rust:nightly
  script:
    - rustup component add rustfmt-preview
    - cargo fmt --version
    - cargo fmt --all -- --check
