before_script:
  - rustc --version
  - git submodule update --init --recursive
  - cd src

stable:
  image: rust:latest
  allow_failure: true
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose

beta:
  image: rustdocker/rust:beta
  allow_failure: true
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose

nightly:
  image: rustdocker/rust:nightly
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose
