before_script:
  - rustc --version
  - git submodule update --init --recursive
  - cd src

oldest-stable:
  image: rust:1.26
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose -- --test-threads=1

stable:
  image: rust:latest
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose -- --test-threads=1

beta:
  image: rustdocker/rust:beta
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose -- --test-threads=1

nightly:
  image: rustdocker/rust:nightly
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose -- --test-threads=1

fmt:
  image: rust:latest
  script:
    - rustup component add rustfmt-preview
    - cargo fmt --version
    - cargo fmt --all -- --check
