dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.26.2
os:
  - linux
  - osx
cache: cargo

before_install:
  - cd src

script:
  - cargo build --all --verbose
  - cargo test --all --verbose -- --test-threads=1
