dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.28.0
os:
  - linux
  - osx
  - windows
cache: cargo

matrix:
  allow_failures:
    - rust: beta

before_install:
  - cd src

script:
  - cargo build --all --verbose
  - cargo test --all --verbose

jobs:
  include:
    - stage: fmt
      install:
        - rustup component add rustfmt-preview
        - cargo fmt --version
      script:
        - cargo fmt --all -- --check

after_success:
  - echo '[profile.release]' >> Cargo.toml
  - echo 'lto = true' >> Cargo.toml
  - cargo build --release
  - strip target/release/aflak

addons:
  artifacts:
    paths:
      - target/release/aflak
    debug: true
