[package]
name = "aflak-backend"
version = "0.1.0"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]

[dependencies]
serde_derive = "1.0"
serde = "1.0"

[dev-dependencies]
serde_json = "1.0"
ron = "0.2"
lazy_static = "1.0"
