[package]
name = "example"
version = "0.1.0"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]

[dependencies]
variant_name_derive = { path = "../" }
variant_name = { path = "../../variant_name" }
