[workspace]
members = [
    "aflak_cake",
    "aflak_plot",
    "aflak_primitives",
    "imgui_file_explorer",
    "node_editor",
    "ui_image1d",
    "ui_image2d",
    "variant_name",
    "variant_name_derive",
]
