[package]
name = "imgui_file_explorer"
version = "0.1.0"
authors = ["Rikuo Uchiki <dbkn_rikuo@keio.jp>"]


[dependencies]
imgui = {path = "../../imgui-rs" }

[dev-dependencies]
glium = { version = "0.20", default-features = true }
imgui-glium-renderer = { path = "../../imgui-rs/imgui-glium-renderer" }
