[package]
name = "aflak_imgui_file_explorer"
version = "0.0.1"
authors = ["Rikuo Uchiki <dbkn_rikuo@keio.jp>"]
description = "File explorer plugin for imgui-rs"
license = "GPL-3.0-only"

[dependencies]
cfg-if = "0.1"
aflak_imgui = {path = "../../imgui-rs", version = "0.18.1" }

[dev-dependencies]
glium = { version = "0.22", default-features = true }
aflak_imgui-glium-renderer = { path = "../../imgui-rs/imgui-glium-renderer", version = "0.18.1" }
